### ISSUE TITLE
Geting HTTP 400 error on post to Notion

### ISSUE THREAD

**Issue by kootstra** [mathix420/notion-charts#27]
In Vercel I can see the following in the realt-time log. Checked to see if the Token_V2 was set according to the one in the cookie and it is identical. So I'm at a loss how to debug this any further.

[GET] /notion-schema/1e697f54ab3f492f89ebed37ee.../7a0a2021487b44c6aab7a975806...
16:00:06:44
init
using Web Server Gateway Interface (WSGI)
[ERROR]	2022-08-23T14:00:09.804Z	ec95284d-...	Got 400 error attempting to POST to queryCollection, with data: {
  "collection": {
    "id": "59d952a6-7796-...",
    "spaceId": "8921877a-..."
  },
  "collectionView": {
    "id": "7a0a2021-487b-...",
    "spaceId": "8921877a-...
  },
  "loader": {
    "filter": [],
    "reducers": {
      "collection_group_results": {
        "limit": 100000,
        "type": "results"
      }
    },
    "searchQuery": "",
    "sort": [
      {
        "property": "j?M]",
        "direction": "ascending"
      }
    ],
    "userTimeZone": "UTC",
    "type": "reducer"
  }
}
Traceback (most recent call last):
File "/var/task/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/var/task/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "./api/main.py", line 140, in get_schema
rows = cv.default_query().execute()
File "/var/task/notion/collection.py", line 410, in execute
self._client.query_collection(
File "/var/task/notion/client.py", line 294, in query_collection
return self._store.call_query_collection(*args, **kwargs)
File "/var/task/notion/store.py", line 350, in call_query_collection
response = self._client.post("queryCollection", data).json()
File "/var/task/notion/client.py", line 260, in post
raise HTTPError(
requests.exceptions.HTTPError: Something went wrong.

**Comment by mathix420** [comment]
Hello @kootstra, thanks for reporting this issue!
I will try to have a look once I got some free time, which is not really the case right now 😐

**Comment by kootstra** [comment]
Understandable, and life takes priority over free software. Take care and if there is anything you need, let me know.

Verstuurd vanaf mijn iPad

Op 25 aug. 2022 om 17:10 heeft Arnaud Gissinger ***@***.***> het volgende geschreven:

﻿

Hello @kootstra<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkootstra&data=05%7C01%7C%7C1da65b5ad97943f64bbf08da86abeaf2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637970370191004900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=br%2Fh7rK5LBShiKjnoxOxosMCtAESUODvST4wZ1qTjYk%3D&reserved=0>, thanks for reporting this issue!
I will try to have a look once I got some free time, which is not really the case right now 😐
